language: node_js
node_js:
- '7'
script:
- npm run codestyle
- npm run build
- npm run test
deploy:
  provider: npm
  email: carlopalinckx@gmail.com
  api_key:
    secure: CAMotVxE4hW3PYQwtjPsI1E9BdP5VQyE4xoaMVm7VepMwxnF2KcoBIY1MUQwgPL5E8SYac0IWx4TY4I+3fV+k0/tcAMYeQIQrL785eZk24huytG0+5EncAwFjqvmt9XgELHC+ViA152/UHcuq4tdkhK/hSWLHcCdw2sUupwdKYTKqY3O30TkTl5suLRr0X6kKiDHBLVq6r5Z6gkoxyAQ23wF1SxODeLkx0lnihLmB5v+0A7kbHqIkn0FdnAVxGg86kRe7O291zBBqgWE/YpF+vjRg6GQSXKkoSFY4G+EB4YdKLMwSayKmBfZeLwDrgW5HKbIp2EulyW0pJzROdfW2FfeC4d3+P+Fz2TmByJL3cOV0p74gLvuD1IVKFJBfULzqb+WC5tLNH/xhid2RdTdOljqlkEUt4ZEd9Z2Incm4SNT1KM/Wp0FPjcCJzGPyd5V9K0Le95YtH6RQDTlm3TTTEYw5N7LVi2r4Eq04yqTy60R/CMNrJABqIHqtncE56lcMXxWvYfQIIWjZlwuXAeUz766RFlh6OWmJ3PJ8SsSSjbdbD5GSxDqJX3V2a66jkaZFycGVSs+Aku9Ahj4tA+vSACUwz0KQmzybkvyDPPbZMUdqAPrYZsPl/hSX0+RH/hNt7cYpHDeCell7tY7gHHGvjfCdTTxPRO0SQYHdK75g6Q=
  skip_cleanup: true
  on:
    tags: true
    branch: master
